function F = chemical_reactor_DCNL_multilinearforms
F.A = @A;
F.J1 = @J1;
F.B = @B;
F.A1 = @A1;
F.J2 = @J2;
F.C = @C;
F.J3 = @J3;
F.B1 = @B1;
F.A2 = @A2;

function A = A(in1,in2)
%A
%    A = A(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    18-Oct-2025 13:34:12

csi_1 = in1(:,1);
csi_2 = in1(:,2);
k_bar = in2(:,2);
t2 = csi_2.^2;
t3 = csi_1.*csi_2.*2.0;
A = reshape([-k_bar-t2,k_bar+t2,-t3,t3-1.0],[2,2]);
end

function J1 = J1(in1,in2)
%J1
%    J1 = J1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    18-Oct-2025 13:34:13

csi_1 = in1(:,1);
J1 = reshape([1.0,0.0,-csi_1,csi_1],[2,2]);
end

function B = B(in1,in2,in3,in4)
%B
%    B = B(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    18-Oct-2025 13:34:13

csi_1 = in1(:,1);
csi_2 = in1(:,2);
v11 = in3(1,:);
v12 = in3(2,:);
v21 = in4(1,:);
v22 = in4(2,:);
t2 = csi_1.*v12.*2.0;
t3 = csi_2.*v11.*2.0;
t4 = csi_2.*v12.*v21.*2.0;
t5 = t2+t3;
t6 = t5.*v22;
B = [-t4-t6;t4+t6];
end

function J2 = J2(in1,in2,in3,in4)
%J2
%    J2 = J2(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    18-Oct-2025 13:34:13

J2 = [0.0;0.0];
end

function A1 = A1(in1,in2,in3,in4)
%A1
%    A1 = A1(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    18-Oct-2025 13:34:13

p12 = in4(2,:);
v11 = in3(1,:);
t2 = p12.*v11;
A1 = [-t2;t2];
end

function C = C(in1,in2,in3,in4,in5)
%C
%    C = C(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    18-Oct-2025 13:34:13

v11 = in3(1,:);
v12 = in3(2,:);
v21 = in4(1,:);
v22 = in4(2,:);
v31 = in5(1,:);
v32 = in5(2,:);
t2 = v11.*v22.*2.0;
t3 = v12.*v21.*2.0;
t4 = v12.*v22.*v31.*2.0;
t5 = t2+t3;
t6 = t5.*v32;
C = [-t4-t6;t4+t6];
end

function J3 = J3(in1,in2,in3,in4,in5)
%J3
%    J3 = J3(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    18-Oct-2025 13:34:13

J3 = [0.0;0.0];
end

function B1 = B1(in1,in2,in3,in4,in5)
%B1
%    B1 = B1(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    18-Oct-2025 13:34:13

B1 = [0.0;0.0];
end

function A2 = A2(in1,in2,in3,in4,in5)
%A2
%    A2 = A2(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    18-Oct-2025 13:34:13

A2 = [0.0;0.0];
end

