function F = love_multilinearforms
F.A = @A;
F.J1 = @J1;
F.B = @B;
F.A1 = @A1;
F.J2 = @J2;
F.C = @C;
F.J3 = @J3;
F.B1 = @B1;
F.A2 = @A2;

function A = A(in1,in2)
%A
%    A = A(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    23-May-2026 19:45:39

KK = in2(:,3);
x1 = in1(:,1);
x2 = in1(:,2);
t2 = -x1;
t3 = -x2;
t4 = exp(t2);
t5 = exp(t3);
A = reshape([-1.0,KK.*t4+KK.*t2.*t4,KK.*t5+KK.*t3.*t5,-1.0],[2,2]);
end

function J1 = J1(in1,in2)
%J1
%    J1 = J1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    23-May-2026 19:45:40

x1 = in1(:,1);
x2 = in1(:,2);
J1 = reshape([0.0,1.0,1.0,0.0,x2.*exp(-x2),x1.*exp(-x1)],[2,3]);
end

function B = B(in1,in2,in3,in4)
%B
%    B = B(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    23-May-2026 19:45:40

KK = in2(:,3);
v11 = in3(1,:);
v12 = in3(2,:);
v21 = in4(1,:);
v22 = in4(2,:);
x1 = in1(:,1);
x2 = in1(:,2);
t2 = -x1;
t3 = -x2;
t4 = exp(t2);
t5 = exp(t3);
B = [-v12.*v22.*(KK.*t5.*2.0+KK.*t3.*t5);-v11.*v21.*(KK.*t4.*2.0+KK.*t2.*t4)];
end

function J2 = J2(in1,in2,in3,in4)
%J2
%    J2 = J2(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    23-May-2026 19:45:40

J2 = [0.0;0.0];
end

function A1 = A1(in1,in2,in3,in4)
%A1
%    A1 = A1(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    23-May-2026 19:45:40

p13 = in4(3,:);
v11 = in3(1,:);
v12 = in3(2,:);
x1 = in1(:,1);
x2 = in1(:,2);
t2 = -x1;
t3 = -x2;
t4 = exp(t2);
t5 = exp(t3);
A1 = [p13.*v12.*(t5+t3.*t5);p13.*v11.*(t4+t2.*t4)];
end

function C = C(in1,in2,in3,in4,in5)
%C
%    C = C(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    23-May-2026 19:45:40

KK = in2(:,3);
v11 = in3(1,:);
v12 = in3(2,:);
v21 = in4(1,:);
v22 = in4(2,:);
v31 = in5(1,:);
v32 = in5(2,:);
x1 = in1(:,1);
x2 = in1(:,2);
t2 = -x1;
t3 = -x2;
t4 = exp(t2);
t5 = exp(t3);
C = [v12.*v22.*v32.*(KK.*t5.*3.0+KK.*t3.*t5);v11.*v21.*v31.*(KK.*t4.*3.0+KK.*t2.*t4)];
end

function J3 = J3(in1,in2,in3,in4,in5)
%J3
%    J3 = J3(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    23-May-2026 19:45:40

J3 = [0.0;0.0];
end

function B1 = B1(in1,in2,in3,in4,in5)
%B1
%    B1 = B1(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    23-May-2026 19:45:40

p13 = in5(3,:);
v11 = in3(1,:);
v12 = in3(2,:);
v21 = in4(1,:);
v22 = in4(2,:);
x1 = in1(:,1);
x2 = in1(:,2);
t2 = -x1;
t3 = -x2;
t4 = exp(t2);
t5 = exp(t3);
B1 = [-p13.*v12.*v22.*(t5.*2.0+t3.*t5);-p13.*v11.*v21.*(t4.*2.0+t2.*t4)];
end

function A2 = A2(in1,in2,in3,in4,in5)
%A2
%    A2 = A2(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    23-May-2026 19:45:40

A2 = [0.0;0.0];
end

